# Generated by Django 4.2.11 on 2026-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_blogs_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='members',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
